### ISSUE TITLE
Assert macro fail in compile.c

### ISSUE THREAD

**Issue by Cube9999** [larmel/lacc#29]
# Description

While compiling a project (https://github.com/viown/SeaScript) I get the following error while trying to compile lexer.c:
![image](https://user-images.githubusercontent.com/70229983/121058618-2679e580-c786-11eb-86df-90a2a5a7ca43.png)

This seems to only occur in lacc. As it compiles just fine in gcc and clang

# Platform
Ubuntu 21.04 x86_64. Lacc built with gcc 10

**Comment by Cube9999** [comment]
I tried compiling some of my own projects (for example, https://github.com/Cube9999/coreutils) and lacc worked flawlessly. So I do not think it's an issue with my build.

**Comment by larmel** [comment]
Thanks for reporting this, it is clearly a bug (assert failure is always a compiler bug). I suppose you made some workaround to  your issue, but I implemented a fix with [830c12aa](https://github.com/larmel/lacc/commit/830c12aa7c62ca47fa74d1cb687131d136da0262).

**Comment by Cube9999** [comment]
Yes, I made a workaround after this. Thank you for pushing your fix!
