### ISSUE TITLE
Add a -s flag that will strip symbols from output after compilation

### ISSUE THREAD

**Issue by sophuric** [larmel/lacc#36]

**Comment by rofl0r** [comment]
your unprofessional, minimalistic issue description leaves it unclear whether you refer to compilation of lacc itself, or the output of it, but either way it's the choice of the user whether he wants -s in his LDFLAGS or not.

**Comment by sophuric** [comment]
sorry, I meant let users add it as an option for compiling

**Comment by sophuric** [comment]
i don't think all compilers are meant to support this, it seems only gcc has this
